import Head from "next/head"

import dynamic from "next/dynamic"
import { Inter } from "@next/font/google"

const LitterWitch = dynamic(() => import("../components/LitterWitch"), {
  ssr: false,
  loading: () => <div>Loading</div>,
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Hallowen character</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LitterWitch />
      </main>
    </>
  )
}
